main: dev.mruniverse.rigoxblocker.RigoxBlocker
version: 1.4
name: RigoxBlocker
author: MrUniverse44
description: Command Blocker
commands:
  rigoxblocker:
    description: Main Plugin command.
  rblocker:
    description: Main Plugin command.
  rb:
    description: Main Plugin command.